### ISSUE TITLE
css 系列 (1)- 使用 flexbox 实现百分比布局

### ISSUE THREAD

**Issue by nfwyst** [nfwyst/Blog#21]
对于百分比布局最常见的方式是使用 width, 但在自适应上缺乏一定的灵活性。 我们有多种方式可以实现百分比布局, 包括 flexbox， 比如我们要实现下面的效果

![屏幕快照 2020-02-25 上午8 58 59](https://user-images.githubusercontent.com/35720450/75204873-1adef700-57ad-11ea-84b5-4e7d7289a96e.png)

# 初始化模板

我们的 html 文件中有8个div, 表示每一个布局块

```html
<div class="wrapper">
  <div class="a">A</div>
  <div class="b">B</div>
  <div class="c">C</div>
  <div class="d">D</div>
  <div class="e">E</div>
  <div class="f">F</div>
  <div class="g">G</div>
  <div class="h">H</div>
</div>
```

接下来给每一个布局块上色
```css
div > div {
  font-size: 5rem;
  text-align: center;
  color: white;
}
.a {
  background-color: #FCB10F;
}
.b {
  background-color: #801340;
}
.c {
  background-color: #4D2975;
}
.d {
  background-color: #244479;
}
.e {
  background-color: #55B4AF;
}
.f {
  background-color: rgba(128, 19, 64, 0.7); 
}
.g {
  background-color: rgba(77, 41, 117, 0.5);
}
.h {
  background-color: rgba(252, 177, 15, 0.7);
}
```

# 布局实现

第一步， 父容器应该是一个 flex 容器
```css
.wrapper {
  display: flex;
  flex-flow: row wrap;
  justify-content: space-between;
  align-content: stretch;
}
```
除了指定 flex 容器， 我们还设置了换行， 每一个布局块之间均匀分布

第二步， 每一个布局块之间添加上下间距
```css
.wrapper > * {
  margin-bottom: 1rem;
}
```

第三步， 为每一个布局块设置初始大小
```css
.a,
.h {
  flex-basis: 66%;
}

.c {
  flex-basis: 100%;
}

.b,
.d,
.e,
.f,
.g {
  flex-basis: 32%;
}
```
这里使用百分比单位作为初始大小, 刷新页面即可看到效果
