### ISSUE TITLE
css 系列(2)-使用 css 实现抽屉式菜单

### ISSUE THREAD

**Issue by nfwyst** [nfwyst/Blog#22]
我们都知道， 抽屉式菜单可以使用 javascript 实现， 但实际上， css 也能实现抽屉式菜单， 这在前端性能优化的时候特别有用, 比如我们要实现下面的效果

![屏幕快照 2020-02-27 上午7 44 42](https://user-images.githubusercontent.com/35720450/75398605-1c3b2b80-5935-11ea-8bc5-687712dcbe54.png)
![屏幕快照 2020-02-27 上午7 44 51](https://user-images.githubusercontent.com/35720450/75398619-25c49380-5935-11ea-88f5-a2ce96f2d086.png)

# 模板代码

首先我们有一个面包屑图标和一个带标题的 logo, 然后有一个导航栏菜单, 并且添加了可访问性元素
```html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <title>菜单</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <script src="https://kit.fontawesome.com/fb7f6f30e4.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Nobile:400,500|Open+Sans&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="./style.css">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <header>
    <section class="row">
      <a href="#main-menu" class="menu-toggle" id="main-menu-toggle" aria-label="Open main menu">
        <span class="sr-only">Open main menu</span>
        <span class="fa fa-bars" aria-hidden="true"></span>
      </a>
      <article class="logo">
        <h1><i class="fas fa-paint-brush"></i>CSS菜单</h1>
        <p>hello world</p>
      </article>
    </section>
    <nav id="main-menu" class="main-menu" aria-label="main menu">
      <a href="#main-menu-toggle" class="menu-close">
        <span class="sr-only">Close main menu</span>
        <span class="fa fa-close" aria-hidden="true"></span>
      </a>
      <ul>
        <li><a href="#">CSS</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">Video</a></li>
        <li><a href="#">Music</a></li>
      </ul>
    </nav>
    <a href="#main-menu-toggle" class="backdrop" hidden tabindex="-1"></a>
  </header>
</body>

</html>
```

我们让 logo 和 面包屑图标显示在一行， 并添加一些初始样式

```css
header .row {
  display: flex;
  flex-flow: row nowrap;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}

.menu-toggle {
  color: #333;
  margin-right: 1rem;
}

.menu-toggle:hover,
.menu-toggle:focus {
  color: #C85028;
}

.main-menu {
  position: fixed;
  display: none;
  background-color: black;
  left: -200px;
  top: 0;
  height: 100%;
  overflow-x: visible;
  overflow-y: auto;
  transition: all .5s ease;
  z-index: 999;
}

.main-menu ul {
  padding-top: 2.5em;
  padding-left: 0;
  min-height: 100%;
  width: 200px;
}

.main-menu ul li {
  display: block;
}

.main-menu a {
  padding: .75em;
  color: #fff;
  border-bottom: 1px solid #383838;
  transition: all .3s ease;
  display: block;
}

.main-menu li:first-child a {
  border-top: 1px solid #383838;
}

.main-menu a:hover,
.main-menu a:focus {
  background: #333;
  text-decoration: underline;
}

.main-menu .menu-close {
  position: absolute;
  right: 0;
  top: 0;
}

header {
  border-bottom: 4px solid #9EA9C1;
}

nav ul {
  list-style: none;
  margin: 0
}

nav a {
  display: block;
  padding: .75rem;
  text-decoration: none;
}

@media (min-width: 800px) {
  header, main {
    border: none;
    margin: 0
  }

  nav {
    /* border-top: 4px solid #9EA9C1; */
    border-bottom: 1px solid #ddd;
    padding: .3rem 0;
  }

  nav ul {
    text-align: center;
  }

  nav li {
    display: inline-block;
  }

  nav a {
    color: #C85028;
    border-bottom: none;
    display: inline;
  }
}
```

最后我们要实现当点击面包屑图标的时候， 弹出左侧的菜单, 点击关闭按钮的时候关闭， 注意我们 html 中设置的 `href="#main-menu-toggle"` 和 `href="#main-menu"` 这两个属性， 现在我们要用到这两个属性

```css
.main-menu:target {
  display: block;
  left: 0;
  outline: none;
}

.main-menu:target .menu-close {
  z-index: 1001;
}

.main-menu:target ul {
  position: relative;
  z-index: 1000;
}

.main-menu:target + .backdrop {
  position: fixed;
  display: block;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 998;
  background-color: rgba(0, 0, 0, .85);
  cursor: default;
  transition: all .5s ease;
}
```

其中 `.main-menu:target` 表示当类为 `main-menu` 的元素被hash地址定位的时候的状态， 也就是浏览器地址变成`test.html#main-menu`的时候的状态， 这个状态可被css使用. 被定位的时候， `main-menu` 会显示， 并且设置了 `z-index` 层级关系， 这样就不会被挡住, 最后类为`backdrop`的a标签作为中间层的整体黑色背景

刷新浏览器， 即可看到效果
